### PR TITLE
Nightly owners: assign testing_master_previous to gkaihorodova

### PR DESCRIPTION
**Pull request by miskopo**
Ganna volunteered for testing_master_previous, that launches on Tuesday.
Update the owner accordingly.

Signed-off-by: Michal Polovka <mpolovka@redhat.com>

### CODE REVIEW

**Comment by gkaihorodova** [comment]
I agree with this change

**Comment by miskopo** [comment]
> I agree with this change. The only thing is Wednesday, not Tuesday

The run itself runs on Tuesday in the night, so it finishes on Wednesday.

**Comment by gkaihorodova** [comment]
> > I agree with this change. The only thing is Wednesday, not Tuesday
> 
> The run itself runs on Tuesday in the night, so it finishes on Wednesday.

Ack. Thank you !

**Review by flo-renaud — APPROVED** [review]
Thanks for helping, @gkaihorodova !

**Comment by netoarmando** [comment]
Deployed.
```diff
@@ -1,7 +1,7 @@
 #Ansible: openclose_testing_master_latest_flo-renaud
 00 23 * * 3 python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_master_latest --repo_path /root/openclose_pr/freeipa --flow ci --branch master --prci_config ipatests/prci_definitions/nightly_latest.yaml --pr_against_upstream False --reviewer flo-renaud
 #Ansible: openclose_testing_master_previous_miskopo
-00 23 * * 2,4 python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_master_previous --repo_path /root/openclose_pr/freeipa --flow ci --branch master --prci_config ipatests/prci_definitions/nightly_previous.yaml --pr_against_upstream False --reviewer miskopo
+00 23 * * 4 python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_master_previous --repo_path /root/openclose_pr/freeipa --flow ci --branch master --prci_config ipatests/prci_definitions/nightly_previous.yaml --pr_against_upstream False --reviewer miskopo
 #Ansible: openclose_testing_master_rawhide_flo-renaud
 00 10 * * 6 python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_master_rawhide --repo_path /root/openclose_pr/freeipa --flow ci --branch master --prci_config ipatests/prci_definitions/nightly_rawhide.yaml --pr_against_upstream False --reviewer flo-renaud
 #Ansible: openclose_testing_ipa-4.6_miskopo
@@ -24,3 +24,5 @@
 00 15 * * 5 python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_ipa-4.9_latest_selinux --repo_path /root/openclose_pr/freeipa --flow ci --branch ipa-4-9 --prci_config ipatests/prci_definitions/nightly_ipa-4-9_latest_selinux.yaml --pr_against_upstream False --reviewer miskopo
 #Ansible: openclose_testing_master_latest_ssidhaye
 00 23 * * 1,5 python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_master_latest --repo_path /root/openclose_pr/freeipa --flow ci --branch master --prci_config ipatests/prci_definitions/nightly_latest.yaml --pr_against_upstream False --reviewer ssidhaye
+#Ansible: openclose_testing_master_previous_gkaihorodova
+00 23 * * 2 python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_master_previous --repo_path /root/openclose_pr/freeipa --flow ci --branch master --prci_config ipatests/prci_definitions/nightly_previous.yaml --pr_against_upstream False --reviewer gkaihorodova
```

**Pull request merged**
