### PR TITLE
Nightly tests: update reviewer for testing_master_previous

### PR DESCRIPTION
**Pull request by flo-renaud**
miskopo agreed to handle testing_master_previous run
from Thursdays.

### CODE REVIEW

**Review by miskopo — APPROVED** [review]

**Comment by netoarmando** [comment]
Change in place as of now.

**Comment by flo-renaud** [comment]
@netoarmando the automation VM hasn't been updated, the latest run for testing_master_previous is still setting ssidhaye as reviewer. Can you update the VM? thanks

**Comment by netoarmando** [comment]
Oh.. The Ansible plabook duplicated the entry on crontab, I've just removed ssidhaye's entry manually. It should be fine now.

**Comment by flo-renaud** [comment]
I think I understand the reason... we now have 2 x openclose_testing_master_previous_miskopo (tuesdays, thursdays). Let me fix that on another PR...

**Comment by flo-renaud** [comment]
https://github.com/freeipa/freeipa-pr-ci/pull/442

**Comment by netoarmando** [comment]
> #442

Thanks for that!

**Pull request merged**
