### PR TITLE
reset Administrator password after configuring AD

### PR DESCRIPTION
**Pull request by wladich**
This fixes https://pagure.io/freeipa/issue/8263

### CODE REVIEW

**Comment by wladich** [comment]
Nightly run illustrating the issue: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/aa5a2b66-9d17-11ea-8cc9-fa163e97aa0c/report.html):
In test_ipa_commands_run_as_aduser command "'kinit Administrator@ad.test" fails with message 
```
ipa: ERROR: stderr: kinit: KDC has no support for encryption type while getting initial credentials
```

The fix was verifyid on private runner: https://github.com/wladich/freeipa/pull/18: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0fa5992c-9f3b-11ea-a65c-fa163e4ad552/report.html) (the two failing tests are also failing in nightly job )

**Comment by wladich** [comment]
@netoarmando 
Please have a look at the PR, we need it to fix the failures in nightly runs on recent Fedoras

**Comment by netoarmando** [comment]
@wladich Does it change something on `test_smb.py`, `test_idviews.py`, `test_winsyncmigrate.py` or any other test that requires AD?

**Comment by wladich** [comment]
What this PR does is re-enabling kinit on IPA as Windows Administrator. I did a quick check and found no other tests that use this pattern besides  test_trust::test_ipa_commands_run_as_aduser.
(This test being broken breaks two following tests because it does not run the teardown part after failure).

**Comment by netoarmando** [comment]
Deployed on gating and nightly runners.

**Pull request merged**
