### PR TITLE
Fix fedora 35 and rawhide images

### PR DESCRIPTION
**Pull request by netoarmando**
* Fix Selenium and Geckodriver steps
  * Selenium moved to Github releases
  * Download latest geckodriver binary
  * Issue: https://pagure.io/freeipa/issue/9029
* Add Fedora 35 vars and bump rawhide release version

### CODE REVIEW

**Comment by netoarmando** [comment]
@flo-renaud I'll upload a new Fedora 35 candidate image based on this. 
This PR might need to be merged because of the "enable swap" step, I'll confirm that while running webui test suite.

**Comment by pvoborni** [comment]
I was reading the code, but did no testing.  The changes looks good to me (provided that they work), except the "swap" commit where I don't understand the motivation, implication and especially what is the trigger for not being a temporary change.

**Comment by netoarmando** [comment]
> I was reading the code, but did no testing. The changes looks good to me (provided that they work), except the "swap" commit where I don't understand the motivation, implication and especially what is the trigger for not being a temporary change.

Fedora 35 images have swap enabled by default, this change has no implications when building the images, it affects only the execution of test jobs. If you go to any successful job log at https://github.com/freeipa-pr-ci2/freeipa/pull/1299 you will see that swap is failing and "vagrant provision" is re-run.

I included that commit as a quick-and-dirty solution. Let me remove that from this PR, open a new one where I check the need to execute or not those steps, leaving here only the changes necessary to build the images.

**Review by flo-renaud — APPROVED** [review]
Hi @netoarmando 
LGTM

**Pull request merged**
