### PR TITLE
do not check gpg signature for test repo

### PR DESCRIPTION
**Pull request by wladich**
Related to #419

### CODE REVIEW

**Comment by wladich** [comment]
#419 was tested on personal runner with Fedora 30 and an old version of ansible. 
Production runners use F32 with more recent version of ansible and packages installation fails there.

I have reproduced the issue on other personal runner with F32: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/fa0751be-7c25-11eb-a439-fa163ef6493f/

Tested the fix on the same runner: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/edcd6c80-7c2f-11eb-9556-fa163ef6493f

**Review by netoarmando — APPROVED** [review]

**Comment by netoarmando** [comment]
Deployed. I added 're-run' to https://github.com/freeipa/freeipa/pull/5594 so we can confirm everything is ok.

**Comment by netoarmando** [comment]
Thanks @wladich for this.

**Comment by wladich** [comment]
I have rebased https://github.com/freeipa/freeipa/pull/5594 to trigger full rebuild as there were few successful tests executed with wrong version of prci

**Pull request merged**
