### PR TITLE
Fixes for F39 runner

### PR DESCRIPTION
**Pull request by pvoborni**
These are fixes to be able to deploy and run task on F39 runner.

Rebased on: https://github.com/freeipa/freeipa-pr-ci/pull/493 

**fix: use ansible.compatibility_mode = "2.0" in Vagrantfiles**

Needed with newer version of Ansible (on F39) so that generated
Ansible inventory is using ansible_host, ansible_user, ansible_password
instead of ansible_ssh_{host,user,password}.

I.e. so that prci can connect to Windows hosts.

**fix: use hashicorp vagrant**

Instead of the one on Fedora.

Reason: atm Fedora 39 has Vagrant 2.3.4, but we need 2.3.9 to fix winrm
auth issue:
```
ERROR warden: Error occurred: An error occurred executing a remote WinRM command.

Shell: Cmd
Command: hostname
Message: Digest initialization failed: initialization error
```

**fix: cleanup vagrant installation**

- remove support for vagrant  < 2.2
- explicitely install vagrant-sshfs plugin

**fix: remove obsolete logging config from service file**

systemd reported that the logging options are obsolete and should be
removed. Thus removing.

**fix: explicitly define spice graphic for Windows vms**

Otherwise it fails with:
```
Error while creating domain: Error saving the server: Call to virDomainDefineXML
failed: unsupported configuration: chardev 'spicevmc' not supported without spice
graphics
```

**fix: comment out configuration of sunrpc**

As it fails on Fedora 39.

**fix: replace remote_user: root with become**

So that the playbook works if Ansible is connecting as a different user.

**fix: change deprecated ansible include to include_tasks**

To remove depracation warning and to work in a future.

### CODE REVIEW

**Comment by pvoborni** [comment]
Testing: I did some testing with my custom runner here - https://github.com/pvoborni/freeipa/pulls - there are various active branches and boxes currently used. 

Based on the above, I've also deployed one F39 runner on parallel infra. It looks to be working (I didn't spot an issue).

**Comment by flo-renaud** [comment]
Hi @pvoborni 
as the runners are f39, they use systemd-resolved and they need to have `/etc/systemd/resolved.conf` with the following line:
```
DNSSEC=yes
```

Otherwise the installation of ipa server detects that the forwarder (=the runner) does not support dnssec and disables dnssec validation. This results in test_upgrade failing: in [PR#38](https://github.com/pvoborni/freeipa/pull/38) we see the failure [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/66f5bd20-8ec9-11ee-b9a4-fa163ee84bdd/report.html?sort=result) and the ipa-server-install.log [file](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/66f5bd20-8ec9-11ee-b9a4-fa163ee84bdd/test_integration-test_upgrade.py-TestUpgrade-install/master.ipa.test/var/log/ipaserver-install.log.gz) shows:
```
2023-11-29T15:12:12Z DEBUG Checking DNS server: 192.168.121.1
2023-11-29T15:12:12Z WARNING DNS server 192.168.121.1 does not support DNSSEC: answer to query '. SOA' is missing DNSSEC signatures (no RRSIG data)
2023-11-29T15:12:12Z WARNING Please fix forwarder configuration to enable DNSSEC support.
```

**Comment by flo-renaud** [comment]
> Added patch to use the `DNSSEC=yes` config. + additional patch to not start PRCI during deployment.
> 
> The DNSSEc patch looks to fix the `test_upgrade` issue. But 2 other jobs started to fail on installing packages via dnf with e.g.
> 
> ```
>  Error: Error downloading packages:
> DEBUG    ipatests.pytest_ipa.integration.host.Host.client0.cmd102:transport.py:557   Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
> DEBUG    ipatests.pytest_ipa.integration.host.Host.client0.cmd102:transport.py:557 Could not install OpenSC package
> ```
> 
> Running `getent ahosts mirrors.fedoraproject.org`, `dig A mirrors.fedoraproject.org` or `dig AAAA mirrors.fedoraproject.org` directly on the runner return IP addresses.
> 
>     * [Nightly tests: test on f38 and f39 pvoborni/freeipa#38](https://github.com/pvoborni/freeipa/pull/38) (I've rebased the PR on current master)
> 
>     * http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/03a20af2-9528-11ee-89c0-fa163e769e2f/
> 
>     * http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e4566c4c-9527-11ee-9e7d-fa163e1ec1dc/

Maybe you can try this setting instead:
DNSSEC=allow-downgrade

**Comment by pvoborni** [comment]
With `DNSSEC=allow-downgrade` I got the same results. (re-ran only the failed jobs, same pr). I wonder if I should investigate - not very exited about it :)

**Comment by flo-renaud** [comment]
Hi @pvoborni 
I have a fix in progress for the tests that are failing with DNSSEC=yes: https://github.com/freeipa/freeipa/pull/7119

IMO you can merge this PR and deploy the runners.

**Review by flo-renaud — APPROVED** [review]

**Pull request merged**
