### PR TITLE
Setup certificate authority on Windows Server

### PR DESCRIPTION
**Pull request by wladich**
Certificate Authority feature is required by test test_winsyncmigrate.py

### CODE REVIEW

**Comment by netoarmando** [comment]
@wladich I've tested these changes on https://github.com/netoarmando/freeipa/pull/27 and I got the following error:
```
2019-11-16 02:46:27,645    DEBUG  TASK [windows/ad-root : setup Certification Authority] *************************
2019-11-16 02:46:51,966    DEBUG  fatal: [ad-root]: FAILED! => {"changed": true, "cmd": "Install-AdcsCertificationAuthority -CAType EnterpriseRootCA -Force", "delta": "0:00:09.406325", "end": "2019-11-16 02:46:50.842136", "msg": "non-zero return code", "rc": 1, "start": "2019-11-16 02:46:41.435811", "stderr": "Install-AdcsCertificationAuthority : Active Directory Certificate Services setup failed with the following error:  A \r\nvalue for the attribute was not in the acceptable range of values. 0x80072082 (WIN32: 8322 ERROR_DS_RANGE_CONSTRAINT)\r\nAt line:1 char:65\r\n+ ... ing $false; Install-AdcsCertificationAuthority -CAType EnterpriseRoot ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (:) [Install-AdcsCertificationAuthority], CertificationAuthoritySetupEx \r\n   ception\r\n    + FullyQualifiedErrorId : SetCAProperties,Microsoft.CertificateServices.Deployment.Commands.CA.InstallADCSCertific \r\n   ationAuthority", "stderr_lines": ["Install-AdcsCertificationAuthority : Active Directory Certificate Services setup failed with the following error:  A ", "value for the attribute was not in the acceptable range of values. 0x80072082 (WIN32: 8322 ERROR_DS_RANGE_CONSTRAINT)", "At line:1 char:65", "+ ... ing $false; Install-AdcsCertificationAuthority -CAType EnterpriseRoot ...", "+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : InvalidArgument: (:) [Install-AdcsCertificationAuthority], CertificationAuthoritySetupEx ", "   ception", "    + FullyQualifiedErrorId : SetCAProperties,Microsoft.CertificateServices.Deployment.Commands.CA.InstallADCSCertific ", "   ationAuthority"], "stdout": "", "stdout_lines": []}
2019-11-16 02:46:51,967    DEBUG  
2019-11-16 02:46:51,967    DEBUG  cmd: Install-AdcsCertificationAuthority -CAType EnterpriseRootCA -Force
2019-11-16 02:46:51,967    DEBUG  
2019-11-16 02:46:51,968    DEBUG  start: 2019-11-16 02:46:41.435811
2019-11-16 02:46:51,968    DEBUG  
2019-11-16 02:46:51,968    DEBUG  end: 2019-11-16 02:46:50.842136
2019-11-16 02:46:51,968    DEBUG  
2019-11-16 02:46:51,969    DEBUG  delta: 0:00:09.406325
2019-11-16 02:46:51,969    DEBUG  
2019-11-16 02:46:51,969    DEBUG  msg: non-zero return code
2019-11-16 02:46:51,969    DEBUG  
2019-11-16 02:46:51,970    DEBUG  stderr: Install-AdcsCertificationAuthority : Active Directory Certificate Services setup failed with the following error:  A 
2019-11-16 02:46:51,970    DEBUG  value for the attribute was not in the acceptable range of values. 0x80072082 (WIN32: 8322 ERROR_DS_RANGE_CONSTRAINT)
2019-11-16 02:46:51,970    DEBUG  At line:1 char:65
2019-11-16 02:46:51,970    DEBUG  + ... ing $false; Install-AdcsCertificationAuthority -CAType EnterpriseRoot ...
2019-11-16 02:46:51,971    DEBUG  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-11-16 02:46:51,971    DEBUG      + CategoryInfo          : InvalidArgument: (:) [Install-AdcsCertificationAuthority], CertificationAuthoritySetupEx 
2019-11-16 02:46:51,971    DEBUG     ception
2019-11-16 02:46:51,971    DEBUG      + FullyQualifiedErrorId : SetCAProperties,Microsoft.CertificateServices.Deployment.Commands.CA.InstallADCSCertific 
2019-11-16 02:46:51,972    DEBUG     ationAuthority
2019-11-16 02:46:51,972    DEBUG  	to retry, use: --limit @/root/freeipa-pr-ci/ansible/provision_ad.retry
2019-11-16 02:46:51,972    DEBUG  
2019-11-16 02:46:51,972    DEBUG  PLAY RECAP *********************************************************************
2019-11-16 02:46:51,972    DEBUG  ad-root                    : ok=13   changed=10   unreachable=0    failed=1   
2019-11-16 02:46:51,973    DEBUG  
2019-11-16 02:46:52,015    DEBUG  Ansible failed to complete successfully. Any error output should be
2019-11-16 02:46:52,016    DEBUG  visible above. Please fix these errors and try again.
```

**Comment by wladich** [comment]
@netoarmando 
It turns out that cert authority must be configured after promoting to AD DC.
I have updated PR, please rerun the tests.

**Comment by netoarmando** [comment]
@wladich newer test results: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/222f5922-0cbd-11ea-876a-fa163e302fbf/

**Comment by wladich** [comment]
The test have successfully retrieved and installed the certificate from AD machine:
```
[ipatests.pytest_ipa.integration.host.WinHost.ad-root.ParamikoTransport] READ /cygdrive/c/Windows/System32/CertSrv/CertEnroll/ad-root.ad.test_ad-AD-ROOT-CA.crt
...
[ipatests.pytest_ipa.integration.host.Host.master.cmd52] Added CA certificate /tmp/tmp.nsXApbQOEH to certificate database for master.ipa.test
```

The test failed during `ipa-replica-manage`:
```
ipa: ERROR: stderr: ipa: INFO: Failed to connect to AD server ad-root.ad.test
ipa: INFO: The error was: {'desc': 'Server is unavailable', 'info': '00000000: LdapErr: DSID-0C091293, comment: Error initializing SSL/TLS, data 0, v3839'}
Failed to setup winsync replication
```

**Comment by netoarmando** [comment]
Thanks @wladich for this! It will be deployed later today.

**Comment by netoarmando** [comment]
Deployed.

**Pull request merged**
