### PR TITLE
Assign ssidhaye's jobs to gkaihorodova

### PR DESCRIPTION
**Pull request by miskopo**
Due to organizational restructuration, assign Sumedh's nightly runs to Ganna.

Signed-off-by: Michal Polovka <mpolovka@redhat.com>

### CODE REVIEW

**Comment by gkaihorodova** [comment]
@miskopo thank you ! 
Yes, I agree with the change

**Review by flo-renaud — APPROVED** [review]
Thanks!

**Comment by netoarmando** [comment]
Deployed to all runners.

**Comment by flo-renaud** [comment]
@netoarmando the change needs to be applied on the automation VM, not on the runners. I manually updated the crontab on production-prci-automation.

**Comment by netoarmando** [comment]
> @netoarmando the change needs to be applied on the automation VM, not on the runners. I manually updated the crontab on production-prci-automation.

You're right! I deployed by instinct without reading the content here. :D Thanks for updating the crontab!

**Pull request merged**
