### PR TITLE
Change value for key of win_security_policy

### PR DESCRIPTION
**Pull request by amore17**
Failures observed in : http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/4a6b8d52-bac3-11ea-88b4-fa163e97fbb7/runner.log.gz

### CODE REVIEW

**Comment by netoarmando** [comment]
Is this directly related to this provisioning failure?
```
TASK [windows/ipa-ad-data : set primary group] *********************************
2020-06-30 12:03:47,433    DEBUG  fatal: [ad-child]: FAILED! => {"changed": true, "cmd": "$username = \"subdomaintestuser\"\n$NewGroup = \"subdomaintestgroup\"\n\nAdd-ADGroupMember -Identity $NewGroup -Members $username\n\n$NewPrimaryGroupToken = (Get-ADGroup $NewGroup -Properties primaryGroupToken).primaryGroupToken\nSet-ADUser -Identity $username -Replace @{primaryGroupID=$NewPrimaryGroupToken}", "delta": "0:00:03.563013", "end": "2020-06-30 12:03:44.615136", "msg": "non-zero return code", "rc": 1, "start": "2020-06-30 12:03:41.052123", "stderr": "Add-ADGroupMember : The global catalog verification failed. The global catalog is not available or does not support \r\nthe operation. Some part of the directory is currently not available\r\nAt line:4 char:1\r\n+ Add-ADGroupMember -Identity $NewGroup -Members $username\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (subdomaintestgroup:ADGroup) [Add-ADGroupMember], ADException\r\n    + FullyQualifiedErrorId : ActiveDirectoryServer:8417,Microsoft.ActiveDirectory.Management.Commands.AddADGroupMembe \r\n   r\r\n \r\nSet-ADUser : The specified user account is not a member of the specified group account\r\nAt line:7 char:1\r\n+ Set-ADUser -Identity $username -Replace @{primaryGroupID=$NewPrimaryG ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (subdomaintestuser:ADUser) [Set-ADUser], ADException\r\n    + FullyQualifiedErrorId : ActiveDirectoryServer:1321,Microsoft.ActiveDirectory.Management.Commands.SetADUser", "stderr_lines": ["Add-ADGroupMember : The global catalog verification failed. The global catalog is not available or does not support ", "the operation. Some part of the directory is currently not available", "At line:4 char:1", "+ Add-ADGroupMember -Identity $NewGroup -Members $username", "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (subdomaintestgroup:ADGroup) [Add-ADGroupMember], ADException", "    + FullyQualifiedErrorId : ActiveDirectoryServer:8417,Microsoft.ActiveDirectory.Management.Commands.AddADGroupMembe ", "   r", " ", "Set-ADUser : The specified user account is not a member of the specified group account", "At line:7 char:1", "+ Set-ADUser -Identity $username -Replace @{primaryGroupID=$NewPrimaryG ...", "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (subdomaintestuser:ADUser) [Set-ADUser], ADException", "    + FullyQualifiedErrorId : ActiveDirectoryServer:1321,Microsoft.ActiveDirectory.Management.Commands.SetADUser"], "stdout": "", "stdout_lines": []}
```

**Comment by netoarmando** [comment]
Some jobs from your test in https://github.com/amore17/freeipa/pull/3 are failing, is it expected?

**Comment by abbra** [comment]
So, I figured out we actually need to use `ksetup` to update existing child-parent domain trust to enable AES encryption types. The corresponding playbook part would be:

```
 cat playbook.yml 
- hosts: ad_root
  tasks:
    - name: Force AES encryption types on subdomains
      loop: "{{ [ (groups.ad_subdomain | map('extract', hostvars) | selectattr('meta_parent_domain', 'equalto', meta_domain) | first).meta_domain | default([]) ] }}"
      win_shell: ksetup /setenctypeattr "{{ item }}" RC4-HMAC-MD5 AES128-CTS-HMAC-SHA1-96 AES256-CTS-HMAC-SHA1-96

    - name: Force AES encryption types on tree domains
      loop: "{{ [ (groups.ad_treedomain | map('extract', hostvars) | selectattr('meta_parent_domain', 'equalto', meta_domain) | first).meta_domain | default([]) ] }}"
      win_shell: ksetup /setenctypeattr "{{ item }}" RC4-HMAC-MD5 AES128-CTS-HMAC-SHA1-96 AES256-CTS-HMAC-SHA1-96

- hosts: ad_subdomain:ad_treedomain
  tasks:
    - name: Force AES encryption types on a trust to parent domain
      win_shell: ksetup /setenctypeattr "{{ meta_parent_domain }}" RC4-HMAC-MD5 AES128-CTS-HMAC-SHA1-96 AES256-CTS-HMAC-SHA1-96

```

See https://support.microsoft.com/en-us/help/4492348/kerberos-unsupported-etype-error-when-authenticating-across-trust, method 1 for details.

**Comment by abbra** [comment]
We need both the change from @amore17 and the change for the playbook above.

**Comment by amore17** [comment]
Tested with fixes : https://github.com/amore17/freeipa/pull/3

**Comment by netoarmando** [comment]
Deployed to all production and nightly runners.

**Comment by abbra** [comment]
Thanks. And `test_trust` succeeded in the latest nightly: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c40a9d00-bdbc-11ea-a6da-fa163e34ae64/report.html
`test_sssd` timed out but this is due to AD child domain failed to set up due to some timing issue: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/edd403f8-bdba-11ea-8454-fa163e4bccbe/runner.log.gz
```
2020-07-04 06:43:52,596    DEBUG  PLAY [ad-child,ad-tree] ********************************************************
2020-07-04 06:43:52,613    DEBUG  
2020-07-04 06:43:52,614    DEBUG  TASK [Gathering Facts] *********************************************************
2020-07-04 06:43:53,180    DEBUG  fatal: [ad-tree]: UNREACHABLE! => {"changed": false, "msg": "ssl: the specified credentials were rejected by the server", "unreachable": true}
2020-07-04 06:44:39,474    DEBUG  ok: [ad-child]
2020-07-04 06:44:39,489    DEBUG  
2020-07-04 06:44:39,490    DEBUG  NO MORE HOSTS LEFT *************************************************************
2020-07-04 06:44:39,498    DEBUG  
2020-07-04 06:44:39,499    DEBUG  PLAY RECAP *********************************************************************
2020-07-04 06:44:39,500    DEBUG  ad-child                   : ok=22   changed=15   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-07-04 06:44:39,500    DEBUG  ad-root                    : ok=29   changed=23   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-07-04 06:44:39,500    DEBUG  ad-tree                    : ok=21   changed=15   unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2020-07-04 06:44:39,500    DEBUG  
2020-07-04 06:44:42,286    DEBUG  Ansible failed to complete successfully. Any error output should be
2020-07-04 06:44:42,287    DEBUG  visible above. Please fix these errors and try again.
2020-07-04 06:44:46,031    DEBUG  Process "vagrant provision" exited with error code 1
Traceback (most recent call last):
  File "/root/freeipa-pr-ci/tasks/common.py", line 135, in __call__
    super(FallibleTask, self).__call__()
  File "/root/freeipa-pr-ci/tasks/common.py", line 122, in __call__
    raise self.exc
  File "/root/freeipa-pr-ci/tasks/common.py", line 105, in __target
    self._run()
  File "/root/freeipa-pr-ci/tasks/common.py", line 179, in _run
    raise PopenException(self)
tasks.common.PopenException: Process "vagrant provision" exited with error code 1
2020-07-04 06:44:46,266    DEBUG  Process "vagrant provision" exited with error code 1
Traceback (most recent call last):
  File "/root/freeipa-pr-ci/tasks/common.py", line 135, in __call__
    super(FallibleTask, self).__call__()
  File "/root/freeipa-pr-ci/tasks/common.py", line 122, in __call__
    raise self.exc
  File "/root/freeipa-pr-ci/tasks/common.py", line 105, in __target
    self._run()
  File "/root/freeipa-pr-ci/tasks/vagrant.py", line 109, in _run
    timeout=None))
  File "/root/freeipa-pr-ci/tasks/common.py", line 80, in execute_subtask
    task()
  File "/root/freeipa-pr-ci/tasks/common.py", line 139, in __call__
    raise exc
  File "/root/freeipa-pr-ci/tasks/common.py", line 135, in __call__
    super(FallibleTask, self).__call__()
  File "/root/freeipa-pr-ci/tasks/common.py", line 122, in __call__
    raise self.exc
  File "/root/freeipa-pr-ci/tasks/common.py", line 105, in __target
    self._run()
  File "/root/freeipa-pr-ci/tasks/common.py", line 179, in _run
    raise PopenException(self)
tasks.common.PopenException: Process "vagrant provision" exited with error code 1
2020-07-04 06:44:46,294     INFO  Retrying provisioning, 3 retries left
2020-07-04 06:44:56,306     INFO  Executing: VagrantProvision
2020-07-04 06:44:56,359     INFO  Executing: Process "vagrant provision"

```

**Pull request merged**
