### PR TITLE
Add Fedora 37 vars

### PR DESCRIPTION
**Pull request by netoarmando**

### CODE REVIEW

**Comment by f-trivino** [comment]
@netoarmando is this one still needed?

**Comment by netoarmando** [comment]
> @netoarmando is this one still needed?

Yes, but we can keep this open until Fedora 37 Final is released, then I update this with proper vars.

**Comment by netoarmando** [comment]
Fedora 37 Final released.

New boxes created based on this PR:

* [ci-master-f36 0.0.8](https://app.vagrantup.com/freeipa/boxes/ci-master-f36/versions/0.0.8)
* [ci-master-f37 0.0.2](https://app.vagrantup.com/freeipa/boxes/ci-master-f37/versions/0.0.2)
* [ci-master-frawhide 0.8.2](https://app.vagrantup.com/freeipa/boxes/ci-master-frawhide/versions/0.8.2)
* [ci-ipa-4-10-f36 0.0.2](https://app.vagrantup.com/freeipa/boxes/ci-ipa-4-10-f36/versions/0.0.2)
* [ci-ipa-4-10-f37 0.0.2](https://app.vagrantup.com/freeipa/boxes/ci-ipa-4-10-f37/versions/0.0.2)
* [ci-ipa-4-9-f36 0.0.3](https://app.vagrantup.com/freeipa/boxes/ci-ipa-4-9-f36/versions/0.0.3)
* [ci-ipa-4-9-f37 0.0.1](https://app.vagrantup.com/freeipa/boxes/ci-ipa-4-9-f37/versions/0.0.1)

**Comment by netoarmando** [comment]
Merging this since https://github.com/freeipa/freeipa/pull/6558 was merged also.

**Pull request merged**
